### ISSUE TITLE
unable to add trusted domains

### ISSUE THREAD

**Issue by awshemant** [Inveniem/nextcloud-azure-aks#2]
Hi , 

Unable to access the Nextcloud from browser due to the Untrusted domain issue.

I have added my application gateway IP to the config.php but unable to access it.

**Comment by GuyPaddock** [comment]
Please try setting up a DNS hostname for that IP and then using the hostname as a trusted host instead. I am not sure if Nextcloud supports running with an IP address as the trusted domain.

Also, you should not have to customize the config.php file yourself. The `config.env` file has a setting called `NEXTCLOUD_TRUSTED_DOMAINS` that it auto-populates for initial installation.

**Comment by GuyPaddock** [comment]
@awshemant I have not heard from you. Please comment by July 1, 2021 to avoid this issue being marked as stale.

**Comment by awshemant** [comment]
@GuyPaddock Added the IP in config.env and it started to work. Thank you!
